---
# nginx

- name: Backup provisioing
  hosts: backup
  vars:
    ansible_user: jim
    ansible_ssh_pass: amanda
    ansible_become_pass: amanda
  become: true
  tasks:
    - name: install an ubuntu desktop
      package:
        name: ubuntu-desktop
        state: latest
      notify: restart host
    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami